### PR TITLE
commit bug fix #2753

### LINKED ISSUE #2753: ESP Grant Manager View Javascript Error
Javascript Error -> Uncaught Error: You cannot apply bindings multiple times to the same element

Steps to replicate
1. Open any ESP project (https://fieldcapture.ala.org.au/project/index/0315f7ee-b584-46e5-8abe-8b292a21f872?template=index)
2. Go to Grant Manager View
3. Click any button that will show the modal window (in this case "Withdraw approval")
4. Click "Cancel" button to close the modal
5. Click the "Withdraw approval" button again

Expected: The modal will pop-up again without any error.

Actual: The modal will not pop-up due to the JS error.

### PR DESCRIPTION
**Pull request by salomon-j**

### CODE REVIEW

File: grails-app/assets/javascripts/projectActivityPlan.js [hunk 1]
```diff
@@ -307,7 +307,11 @@ var PlanStage = function (stage, activities, planViewModel, isCurrentStage, proj
                 self.updateStageStatus(url, this.reason(), this.rejectionCategory());
             }
         };
-        ko.applyBindings(reasonViewModel, $reasonModal[0]);
+
+        var hasDataBinding = !!ko.dataFor($reasonModal[0]);
+        if (!hasDataBinding) {
+            ko.applyBindings(reasonViewModel, $reasonModal[0]);
+        }
         $reasonModal.modal({backdrop: 'static', keyboard:true, show:true}).on('hidden', function() {ko.cleanNode($reasonModal[0])});
```
Comment (chrisala) [inline grails-app/assets/javascripts/projectActivityPlan.js:315]: The actual fix here is to listen to the correct event - the problem here is the models in bs4 fire 'hidden.bs.modal', not 'hidden'.  (See equivalent in reporting.js).
There are two places in this file with this bug, can you fix the other one while you are fixing this?  Thanks.

**Review by chrisala — CHANGES_REQUESTED** [review]

**Review by chrisala — APPROVED** [review]
